### ISSUE TITLE
Publish Chrome Extension

### ISSUE THREAD

**Issue by codyhxyz** [arnoson/hydra-midi#1]
I see this project hasn't been active for a while but I'd love to see a chrome extension out (or possibly an atom package) that would make MIDI more usable for hydra performances. The main project page mentions that this is coming soon, so I thought making an Issue for it would be a good idea--seems like the most logical next step for this project.

**Comment by arnoson** [comment]
Great to see intereset in the project! I'm very busy until the end of next month, but after that I want to get back at hydra midi. I'm not sure about the chrome extension anymore though, as I just recenetly have learned that hydra can also [load scripts directly](https://github.com/hydra-synth/hydra#loading-external-scripts), maybe this is the way to go.

**Comment by arnoson** [comment]
Closing this, as hydra-midi can now be used with hydra's `loadScript` (see readme).
