### ISSUE TITLE
Add parameter to change middle C

### ISSUE THREAD

**Issue by geikha** [arnoson/hydra-midi#10]
https://github.com/arnoson/hydra-midi/blob/main/src/utils/getNoteNumber.js

**Comment by arnoson** [comment]
Are there any specifications on what is commonly used as the middle C?

**Comment by arnoson** [comment]
Did some research and C4 seems to be the most popular, I'm not sure why I ended up using C3 in the first place. Should we just use C4 (without any parameter to change it)?
