### ISSUE TITLE
Possible to see which note was pressed in the onNote wildcard callback?

### ISSUE THREAD

**Issue by terribleben** [arnoson/hydra-midi#14]
Hello! Thank you for making a cool library!

Suppose I want to switch between a couple hydra scenes:
```
scene1 = () => solid(1,0,0).out()
scene2 = () => solid(0,1,0).out()
```

It would be nice if I could do this:

```const myController = midi.input(0).channel(9);
myController.onNote('*', (note) => {
  switch (note) {
    case 36: { scene1(); break; }
    case 37: { scene2(); break; }
  }
});
```

Instead of this:

```
myController.onNote(36, scene1);
myController.onNote(37, scene2);
```

My code example is kind of contrived, but hopefully you can see how this might be useful in a more dynamic situation that depends on a wide range of note values.

I'm not super familiar with typescript but it looks like this information might be readily available and just isn't passed to the callback right now. Would it be possible to get it?

**Comment by arnoson** [comment]
Glad you like it!
The listeners are called [here](https://github.com/arnoson/hydra-midi/blob/6876752ae33eb1a2887d10b8bd4c29b9617568f9/src/midiAccess.ts#L82) and [here](https://github.com/arnoson/hydra-midi/blob/6876752ae33eb1a2887d10b8bd4c29b9617568f9/src/midiAccess.ts#L87). Should be easy to pass the note information as an argument to the listener. I am still on holiday, so I'll have to see when I'll find some time to look into this.

**Comment by kaosbeat** [comment]
I like it too :-)

I was having the same train of thoughts though, to set my randomseed to the latest note played. I cannot seem to fetch that information from the current implementation.

Typescript noob here, also no Idea how to get this compiled down to the eventual index.js

but would it be something like 

` noteOnEvents.get(noteId)?.(note)`
 
 and changing the [noteOnEvents](https://github.com/arnoson/hydra-midi/blob/6876752ae33eb1a2887d10b8bd4c29b9617568f9/src/state.ts#L20)

```
export default {
  ccValues,

  playingNotes: new Map<string, number>(),

  noteOnEvents: new Map<string, (note: number) => void>(),

  defaults: {
    channel: '*',
    input: '*',
    adsr: [100, 100, 1, 100],
  } as Defaults,
}

```
or is that optimistic simplistic?

**Comment by kaosbeat** [comment]
works perfectly, thanks!

**Comment by arnoson** [comment]
Great, thanks for testing it!

@kaosbeat this would only change the function signature, but the note would still have to be passed when calling the events (see my first comment).

@terribleben your example should work now too (I also added it to the readme :) Here is a [sketch](https://hydra.ojack.xyz/?code=YXdhaXQlMjBsb2FkU2NyaXB0KCdodHRwcyUzQSUyRiUyRmNkbi5qc2RlbGl2ci5uZXQlMkZucG0lMkZoeWRyYS1taWRpJTQwMC40LjElMkZkaXN0JTJGaW5kZXguanMnKSUwQWF3YWl0JTIwbWlkaS5zdGFydCglN0IlMjBjaGFubmVsJTNBJTIwJyonJTJDJTIwaW5wdXQlM0ElMjAnKiclMjAlN0QpJTBBbWlkaS5zaG93KCklMEElMEFteUNvbnRyb2xsZXIlMjAlM0QlMjBtaWRpLmlucHV0KDApLmNoYW5uZWwoJyonKSUwQSUwQXNjZW5lMSUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwc29saWQoMSUyQyUyMDAlMkMlMjAwKS5vdXQoKSUwQXNjZW5lMiUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwc29saWQoMCUyQyUyMDElMkMlMjAwKS5vdXQoKSUwQSUwQW15Q29udHJvbGxlci5vbk5vdGUoJyonJTJDJTIwKCU3QiUyMG5vdGUlMkMlMjB2ZWxvY2l0eSUyQyUyMGNoYW5uZWwlMjAlN0QpJTIwJTNEJTNFJTIwJTdCJTBBJTIwJTIwc3dpdGNoJTIwKG5vdGUpJTIwJTdCJTBBJTIwJTIwJTIwJTIwY2FzZSUyMDM2JTNBJTIwJTdCJTIwc2NlbmUxKCklM0IlMjBicmVhayUzQiUyMCU3RCUwQSUyMCUyMCUyMCUyMGNhc2UlMjAzNyUzQSUyMCU3QiUyMHNjZW5lMigpJTNCJTIwYnJlYWslM0IlMjAlN0QlMEElMjAlMjAlN0QlMEElN0Qp)

**Comment by terribleben** [comment]
Thank you! I really appreciate it :)
