### ISSUE TITLE
Saving value into sessionStorage

### ISSUE THREAD

**Issue by genbs** [arnoson/hydra-midi#6]
What if you saved the values in the session storage? So when reloading a script the default values are those entered in the previous session, in case I could open a PR. 🍀

**Comment by arnoson** [comment]
Do you mean the values passed to `midi.start()`? I would consider these settings per project and not global

**Comment by genbs** [comment]
Sorry I haven't been more specific.

I found it useful for faders/knobs (`cc`, `_cc` functions) to save the status so that when reloading a script you don’t have to physically touch them.

For example, with such a script, if you change the `scale` value  the `shape` will always start with the black color (0, 0, 0)

```js
await loadScript(
  'https://cdn.jsdelivr.net/gh/arnoson/hydra-midi@latest/dist/index.js'
)

midi.start({ input: '*', channel: '*' })
midi.show()

solid(cc(1), cc(2), cc(3))
   .scale(.5)
   .out()
```

**Comment by arnoson** [comment]
Ah now I get it! Yes this sounds like a really useful feature, feel free to create a PR (:
